include: package:lints/recommended.yaml

formatter:
  page_width: 80
  trailing_commas: preserve

linter:
  rules:
    - always_use_package_imports
    - lines_longer_than_80_chars
    - directives_ordering
